image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - coenraads.bracket-pair-colorizer
    - vscodevim.vim
    - wakatime.vscode-wakatime

tasks:
  - init: yarn install
    command: yarn
